### ISSUE TITLE
rsc.tl.umap raising ValueError when using neighbors generated by bbknn(metric='angular')

### ISSUE THREAD

**Issue by SNOL2** [scverse/rapids_singlecell#234]
Hi, thanks for this wonderful tool! I encountered an error when applying rsc.tl.umap. Neighbor graph was generated by bbknn(metric='angular'). In addition, do you have any suggestion in gpu-acclerated bbknn? Thanks in advance!

```
Traceback (most recent call last):
  File "umap.pyx", line 460, in cuml.manifold.umap.UMAP._build_umap_params
KeyError: 'angular'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/rapids_singl
ecell/tools/_umap.py", line 180, in umap
    X_umap = umap.fit_transform(X_contiguous)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cuml/interna
ls/api_decorators.py", line 188, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cuml/interna
ls/api_decorators.py", line 393, in dispatch
    return self.dispatch_func(func_name, gpu_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cuml/interna
ls/api_decorators.py", line 190, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "base.pyx", line 687, in cuml.internals.base.UniversalBase.dispatch_func
  File "umap.pyx", line 666, in cuml.manifold.umap.UMAP.fit_transform
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cuml/interna
ls/api_decorators.py", line 188, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cuml/interna
ls/api_decorators.py", line 393, in dispatch
    return self.dispatch_func(func_name, gpu_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre1/zeminz_pkuhpc/lingxinnan/anaconda3/envs/rapids_singlecell/lib/python3.11/site-packages/cuml/interna
ls/api_decorators.py", line 190, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "base.pyx", line 687, in cuml.internals.base.UniversalBase.dispatch_func
  File "umap.pyx", line 585, in cuml.manifold.umap.UMAP.fit
  File "umap.pyx", line 468, in cuml.manifold.umap.UMAP._build_umap_params
ValueError: Invalid value for metric: angular
```

**Comment by Intron7** [comment]
@SNOL2

Sorry for only answering this now. Neighbors and by extension umap doesnt have that distance metric that explains the bug
